export const MARKETPLACE_SECTION_POPULAR = "popular";
export const MARKETPLACE_SECTION_CODE_QUALITY = "code-quality";
export const MARKETPLACE_SECTION_TEAM_COORDINATION = "team-coordination";
export const MARKETPLACE_SECTION_PROJECT_MANAGEMENT = "project-management";
export const MARKETPLACE_SECTION_RESEARCH = "research";
export const MARKETPLACE_SECTION_RELIABILITY = "reliability";

export type MarketplaceSectionId =
  | typeof MARKETPLACE_SECTION_POPULAR
  | typeof MARKETPLACE_SECTION_CODE_QUALITY
  | typeof MARKETPLACE_SECTION_TEAM_COORDINATION
  | typeof MARKETPLACE_SECTION_PROJECT_MANAGEMENT
  | typeof MARKETPLACE_SECTION_RESEARCH
  | typeof MARKETPLACE_SECTION_RELIABILITY;
