import { I18nKey } from "#/i18n/declaration";
import type { MarketplaceSectionId } from "./marketplace-section-ids";
import {
  MARKETPLACE_SECTION_CODE_QUALITY,
  MARKETPLACE_SECTION_POPULAR,
  MARKETPLACE_SECTION_PROJECT_MANAGEMENT,
  MARKETPLACE_SECTION_RELIABILITY,
  MARKETPLACE_SECTION_RESEARCH,
  MARKETPLACE_SECTION_TEAM_COORDINATION,
} from "./marketplace-section-ids";

export interface MarketplaceSectionDefinition {
  id: MarketplaceSectionId;
  labelKey:
    | typeof I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_POPULAR
    | typeof I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_CODE_QUALITY
    | typeof I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_TEAM_COORDINATION
    | typeof I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_PROJECT_MANAGEMENT
    | typeof I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_RESEARCH
    | typeof I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_RELIABILITY;
}

export const MARKETPLACE_SECTIONS: MarketplaceSectionDefinition[] = [
  {
    id: MARKETPLACE_SECTION_POPULAR,
    labelKey: I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_POPULAR,
  },
  {
    id: MARKETPLACE_SECTION_CODE_QUALITY,
    labelKey: I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_CODE_QUALITY,
  },
  {
    id: MARKETPLACE_SECTION_TEAM_COORDINATION,
    labelKey: I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_TEAM_COORDINATION,
  },
  {
    id: MARKETPLACE_SECTION_PROJECT_MANAGEMENT,
    labelKey: I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_PROJECT_MANAGEMENT,
  },
  {
    id: MARKETPLACE_SECTION_RESEARCH,
    labelKey: I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_RESEARCH,
  },
  {
    id: MARKETPLACE_SECTION_RELIABILITY,
    labelKey: I18nKey.AUTOMATIONS$MARKETPLACE_SECTION_RELIABILITY,
  },
];
